version: '1'
services:
  front:
    container_name: front
    restart: always
    build: ./CPMS_FrontEnd
    ports:
     - "8080:8080"
    depends_on:
     - mongo
     - back
  back:
    container_name: back
    restart: always
    build: ./CPMS_BackEnd
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: "mongo"
    #environment:
    #  MONGO_INITDB_DATABASE: CPMS
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"